"""Unit tests for `src/utils/diff_filter.py`."""
import pytest

from src.utils.diff_filter import (
    count_diff_lines,
    is_generated_patch,
    is_skippable_path,
    partition_files,
)


# ---------------------------------------------------------------------------
# is_skippable_path
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("path", [
    "package-lock.json",
    "frontend/package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "npm-shrinkwrap.json",
    "poetry.lock",
    "services/api/Pipfile.lock",
    "uv.lock",
    "rust/Cargo.lock",
    "Gemfile.lock",
    "composer.lock",
    "go.sum",
])
def test_lockfiles_are_skipped(path):
    assert is_skippable_path(path) is True


@pytest.mark.parametrize("path", [
    "node_modules/foo/bar.ts",
    "frontend/node_modules/lodash/index.js",
    "vendor/pkg/file.go",
    "dist/bundle.js",
    "build/out.css",
    ".next/server/pages/foo.js",
    "src/__pycache__/mod.cpython-313.pyc",
    ".venv/lib/site-packages/x.py",
    "venv/bin/activate",
])
def test_vendored_paths_are_skipped(path):
    assert is_skippable_path(path) is True


@pytest.mark.parametrize("path", [
    "static/js/app.min.js",
    "public/css/theme.min.css",
])
def test_minified_assets_are_skipped(path):
    assert is_skippable_path(path) is True


@pytest.mark.parametrize("path", [
    "src/foo.ts",
    "src/components/Button.tsx",
    "backend/app/main.py",
    "README.md",
    "my_vendor_lib/foo.go",   # 'vendor' must be a whole segment
    "docs/build-system.md",    # 'build' must be a whole segment
    "tests/test_config.py",
])
def test_normal_paths_are_kept(path):
    assert is_skippable_path(path) is False


def test_empty_path_is_not_skipped():
    assert is_skippable_path("") is False


# ---------------------------------------------------------------------------
# is_generated_patch
# ---------------------------------------------------------------------------

def test_generated_marker_in_added_lines():
    patch = (
        "@@ -0,0 +1,3 @@\n"
        "+// @generated\n"
        "+export const x = 1;\n"
        "+export const y = 2;\n"
    )
    assert is_generated_patch(patch) is True


def test_autogenerated_marker():
    patch = (
        "@@ -0,0 +1,2 @@\n"
        "+# AUTOGENERATED FILE — DO NOT MODIFY\n"
        "+x = 1\n"
    )
    assert is_generated_patch(patch) is True


def test_do_not_edit_marker():
    patch = (
        "@@ -0,0 +1,2 @@\n"
        "+// DO NOT EDIT — regenerate via scripts/gen.sh\n"
        "+struct S {}\n"
    )
    assert is_generated_patch(patch) is True


def test_code_generated_by_marker():
    patch = (
        "@@ -0,0 +1,2 @@\n"
        "+// Code generated by protoc-gen-go. DO NOT EDIT.\n"
        "+package pb\n"
    )
    assert is_generated_patch(patch) is True


def test_non_generated_patch():
    patch = (
        "@@ -1,3 +1,4 @@\n"
        " def foo():\n"
        "-    return 1\n"
        "+    return 2\n"
        "+    # bumped\n"
    )
    assert is_generated_patch(patch) is False


def test_marker_far_from_header_not_detected():
    # Build a patch with 25 non-marker added lines first, then the marker.
    body = "\n".join(f"+line {i}" for i in range(25))
    patch = f"@@ -0,0 +1,26 @@\n{body}\n+// @generated\n"
    # Scanner stops after ~20 added lines, so this must NOT be flagged.
    assert is_generated_patch(patch) is False


def test_empty_patch():
    assert is_generated_patch("") is False


# ---------------------------------------------------------------------------
# count_diff_lines
# ---------------------------------------------------------------------------

def test_count_diff_lines_ignores_file_headers():
    patch = (
        "--- a/foo.py\n"
        "+++ b/foo.py\n"
        "@@ -1,3 +1,4 @@\n"
        " import os\n"
        "-old_line\n"
        "+new_line_one\n"
        "+new_line_two\n"
    )
    # 1 removed + 2 added. File headers and context lines don't count.
    assert count_diff_lines(patch) == 3


def test_count_diff_lines_only_additions():
    patch = (
        "@@ -0,0 +1,3 @@\n"
        "+a\n"
        "+b\n"
        "+c\n"
    )
    assert count_diff_lines(patch) == 3


def test_count_diff_lines_only_deletions():
    patch = (
        "@@ -1,3 +0,0 @@\n"
        "-a\n"
        "-b\n"
        "-c\n"
    )
    assert count_diff_lines(patch) == 3


def test_count_diff_lines_context_only():
    patch = (
        "@@ -1,2 +1,2 @@\n"
        " a\n"
        " b\n"
    )
    assert count_diff_lines(patch) == 0


def test_count_diff_lines_empty():
    assert count_diff_lines("") == 0


# ---------------------------------------------------------------------------
# partition_files helper
# ---------------------------------------------------------------------------

def test_partition_files_drops_lockfile_and_generated():
    files = [
        {"filename": "src/foo.py", "patch": "+print('x')\n"},
        {"filename": "package-lock.json", "patch": "+{ }\n"},
        {"filename": "src/bar.py",
         "patch": "@@ -0,0 +1,1 @@\n+// @generated\n"},
        {"filename": "node_modules/foo.js", "patch": "+x\n"},
        {"filename": "src/keep.py", "patch": "+ok\n"},
    ]
    kept, skipped = partition_files(files)
    kept_names = {f["filename"] for f in kept}
    assert kept_names == {"src/foo.py", "src/keep.py"}
    assert set(skipped) == {
        "package-lock.json",
        "src/bar.py",
        "node_modules/foo.js",
    }


def test_partition_files_respects_custom_patch_key():
    files = [
        {"filename": "src/foo.py", "diff": "+x\n"},
        {"filename": "yarn.lock", "diff": "+y\n"},
    ]
    kept, skipped = partition_files(files, patch_key="diff")
    assert [f["filename"] for f in kept] == ["src/foo.py"]
    assert skipped == ["yarn.lock"]
