"""Pure helpers for filtering low-value files from PR/MR diffs.

Nothing here imports platform SDKs, Settings, or the agent — it's purely
string/regex-based so it is cheap to unit test and safe to call from any layer.
"""
from __future__ import annotations

import os
from typing import Iterable

# Exact filename matches (lockfiles). We compare against the basename so a
# lockfile nested under a subdirectory is still caught.
_LOCKFILE_BASENAMES: frozenset[str] = frozenset({
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "npm-shrinkwrap.json",
    "poetry.lock",
    "Pipfile.lock",
    "uv.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "composer.lock",
    "go.sum",
})

# Directory segments we never want to review. Match is segment-aware, i.e.
# `vendor/foo.go` skips but `my_vendor_lib/foo.go` does NOT.
_VENDOR_SEGMENTS: tuple[str, ...] = (
    "vendor",
    "node_modules",
    "dist",
    "build",
    ".next",
    "__pycache__",
    ".venv",
    "venv",
)

# Minified bundle suffixes.
_MINIFIED_SUFFIXES: tuple[str, ...] = (".min.js", ".min.css")

# Markers that flag a file as generated when they appear near the top of the
# added content. Matched case-insensitively.
_GENERATED_MARKERS: tuple[str, ...] = (
    "@generated",
    "AUTOGENERATED",
    "DO NOT EDIT",
    "Code generated by",
)

# Number of patch lines to inspect for generated-file markers.
_GENERATED_HEADER_LINES = 20


def _normalize(path: str) -> str:
    """Normalize separators so Windows-style paths also work."""
    return path.replace("\\", "/").lstrip("/")


def _path_segments(path: str) -> list[str]:
    return [seg for seg in _normalize(path).split("/") if seg]


def is_skippable_path(path: str) -> bool:
    """Return True if `path` is a lockfile, vendored dir, or minified asset.

    Matching rules:
      * basename matches any entry in `_LOCKFILE_BASENAMES`
      * any path segment equals a vendored directory name
      * suffix is `.min.js` or `.min.css`
    """
    if not path:
        return False

    norm = _normalize(path)
    basename = os.path.basename(norm)

    if basename in _LOCKFILE_BASENAMES:
        return True

    lower = norm.lower()
    if lower.endswith(_MINIFIED_SUFFIXES):
        return True

    segments = _path_segments(norm)
    vendor_set = set(_VENDOR_SEGMENTS)
    for seg in segments:
        if seg in vendor_set:
            return True

    return False


def is_generated_patch(patch: str) -> bool:
    """Return True if the diff appears to come from a generated file.

    Only the first ~20 *added* lines are inspected — generated-file markers
    typically sit in the file header.
    """
    if not patch:
        return False

    lines_checked = 0
    for raw in patch.splitlines():
        # Skip diff headers ('+++', '---') and hunk markers ('@@ ...').
        if raw.startswith("+++") or raw.startswith("---"):
            continue
        if raw.startswith("@@"):
            continue
        # Only look at added lines and context lines that live inside the file.
        if raw.startswith("+"):
            content = raw[1:]
        elif raw.startswith(" ") or raw == "":
            content = raw[1:] if raw.startswith(" ") else raw
        else:
            # '-' (removed) lines or arbitrary text — ignore for generated detection.
            continue

        lines_checked += 1
        if lines_checked > _GENERATED_HEADER_LINES:
            break

        for marker in _GENERATED_MARKERS:
            # `@generated` and the human-readable phrases we compare case-insensitively;
            # ALL-CAPS markers match exactly anywhere in the line.
            if marker in content:
                return True
            if marker.lower() in content.lower():
                return True

    return False


def count_diff_lines(patch: str) -> int:
    """Count added+removed lines in a unified diff.

    A line counts if it starts with a single `+` or `-` AND is not part of
    the file header (`+++` / `---`). Context lines (starting with a space)
    and hunk markers (`@@`) do not count.
    """
    if not patch:
        return 0

    total = 0
    for line in patch.splitlines():
        if line.startswith("+++") or line.startswith("---"):
            continue
        if line.startswith("+") or line.startswith("-"):
            total += 1
    return total


def partition_files(
    files: Iterable[dict],
    *,
    patch_key: str = "patch",
    path_key: str = "filename",
) -> tuple[list[dict], list[str]]:
    """Split `files` into (keep, skipped_paths).

    Used by platform tools to drop vendored / generated / minified entries
    before they reach the agent.
    """
    kept: list[dict] = []
    skipped: list[str] = []
    for f in files:
        path = f.get(path_key) or ""
        patch = f.get(patch_key) or ""
        if is_skippable_path(path) or is_generated_patch(patch):
            skipped.append(path)
            continue
        kept.append(f)
    return kept, skipped
